In [ ]:
# 3-01. Language Model
# NOTE : What can we do using Language Model?
# NOTE : Why infer next word?

In [4]:
# 3.02. SLM

In [ ]:
# 3.03. N-gram Language Model
"""
one-line summary : Considering certain count of N words to expect next word more accuratly.
connection or question : I can extract better 10 social dimensions from text. if precedure word from the word representing 10 social dimensions
"""

'\none-line summary : Considering certain count of N words to expect next word more accuratly.\nconnection or question : if \n'

In [1]:
# 3.04. Language Model in Korean
"""
one-line summary : Predicting the next word in Korean is challenging for Language Models dut to its flexible word order, agglutinative nature, and inconsistent spacing.
connection or question : How can we improve prediction accuracy for Korean?
"""

'\none-line summary : Predicting the next word in Korean is challenging for Language Models dut to its flexible word order, agglutinative nature, and inconsistent spacing.\nconnection or question : How can we improve prediction accuracy for Korean?\n'

In [2]:
# 3.05. Perplecity
"""
one-line summary : Perplexity is a metric used to measure a language model's accuracy, indicating how uncertain the model is about its predictions.
connection or quesion : Can Perplexity be used to measure a model's performance across the 10 social dimensions it predicted?
"""

"\none-line summary : Perplexity is a metric used to measure a language model's accuracy, indicating how uncertain the model is about its predictions.\nconnection or quesion : Can Perplexity be used to measure a model's performance across the 10 social dimensions it predicted?\n"

In [1]:
# 4.01. Various Ways to represent words
"""
one-line summary : Words representations can broadly be divided into two categories: local(or discrete) representations and continuous representations. 
connection or question : Would continuous representations be more suitable for predicting the 10 social dimensions?
"""

'\none-line summary : Words representations can broadly be divided into two categories: local(or discrete) representations and continuous representations. \nconnection or question : Would continuous representations be more suitable for predicting the 10 social dimensions?\n'

In [3]:
# 4.02. Bag of Words (BoW)
"""
one-line summary : BoW is a simple text representation model that disregards word order and focuses soley on the frequency of words within a document.
connection or question : Can I analyze sentences  categorized by 10 social dimensions using the BoW model?
"""

'\none-line summary : BoW is a simple text representation model that disregards word order and focuses soley on the frequency of words within a document.\nconnection or question : Can I analyze sentences  categorized by 10 social dimensions using the BoW model?\n'

In [4]:
# BoW function
from konlpy.tag import Okt

okt = Okt()

def build_bag_of_words(document):
  # 온점 제거 및 형태소 분석
  document = document.replace('.', '')
  tokenized_document = okt.morphs(document)

  word_to_index = {}
  bow = []

  for word in tokenized_document:  
    if word not in word_to_index.keys():
      word_to_index[word] = len(word_to_index)  
      # BoW에 전부 기본값 1을 넣는다.
      bow.insert(len(word_to_index) - 1, 1)
    else:
      # 재등장하는 단어의 인덱스
      index = word_to_index.get(word)
      # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다.
      bow[index] = bow[index] + 1

  return word_to_index, bow

In [5]:
doc1 = "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다."
vocab, bow = build_bag_of_words(doc1)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
bag of words vector : [1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


In [6]:
doc2 = '소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.'

vocab, bow = build_bag_of_words(doc2)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

vocabulary : {'소비자': 0, '는': 1, '주로': 2, '소비': 3, '하는': 4, '상품': 5, '을': 6, '기준': 7, '으로': 8, '물가상승률': 9, '느낀다': 10}
bag of words vector : [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1]


In [7]:
doc3 = doc1 + ' ' + doc2
vocab, bow = build_bag_of_words(doc3)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9, '는': 10, '주로': 11, '소비': 12, '상품': 13, '을': 14, '기준': 15, '으로': 16, '느낀다': 17}
bag of words vector : [1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print('bag of words vector :', vector.fit_transform(corpus).toarray()) 

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print('vocabulary :',vector.vocabulary_)

bag of words vector : [[1 1 2 1 2 1]]
vocabulary : {'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)

bag of words vector : [[1 1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [10]:
text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)

bag of words vector : [[1 1 1]]
vocabulary : {'family': 0, 'important': 1, 'thing': 2}


In [11]:
text = ["Family is not an important thing. It's everything."]
stop_words = stopwords.words("english")
vect = CountVectorizer(stop_words=stop_words)
print('bag of words vector :',vect.fit_transform(text).toarray()) 
print('vocabulary :',vect.vocabulary_)

bag of words vector : [[1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [12]:
# 4.03. Document-Term Matrix(DTM)
"""
one-line summary : DTM is created by compliling individual BoW representations into a single matrix. However, it often faces two main limitations : the sparsity problem and its sole reliance on word frequency.
connnection or question : Can I use a DTM to alnalyze sentences, especially those containing specific social dimensions?
"""

'\none-line summary : DTM is created by compliling individual BoW representations into a single matrix. However, it often faces two main limitations : the sparsity problem and its sole reliance on word frequency.\nconnnection or question : Can I use a DTM to alnalyze sentences, especially those containing specific social dimensions?\n'

In [23]:
# 4.04. Term Frequency-Inverse Document Frequency (TF-IDF)
"""
one-line summary : TF-IDF is a metric that assigns a weight to each word, allowing us to consider more information than with a simple DTM.
connection or question : Can I use TF-IDF to identify the most important words within the 10 social dimensions?
"""

'\none-line summary : TF-IDF is a metric that assigns a weight to each word, allowing us to consider more information than with a simple DTM.\nconnection or question : Can I use TF-IDF to identify the most important words within the 10 social dimensions?\n'

In [15]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()


In [16]:
# 총 문서의 수
N = len(docs) 

def tf(t, d):
  return d.count(t)

def idf(t):
  df = 0
  for doc in docs:
    df += t in doc
  return log(N/(df+1))

def tfidf(t, d):
  return tf(t,d)* idf(t)


In [19]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [20]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
idf_

IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [21]:
result = []
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(corpus).toarray())

# 각 단어와 맵핑된 인덱스 출력
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
# 05.01 Cosine Similarity
"""
one-line summary : Cosine Similarity  a metric used to measure the imilarity between documents.
connection or question : Can I use Cosine Similaryity to measure the similarity between representations of certain social dimensions?
notation : Cosine Similarity helps when the lengths of documents are different.
"""

'\none-line summary : Cosine Similarity  a metric used to measure the imilarity between documents.\nconnection or question : Can I use Cosine Similaryity to measure the similarity between representations of certain social dimensions?\nnotation \n'

In [26]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
doc3 = np.array([2,0,2,2])

print('문서 1과 문서2의 유사도 :',cos_sim(doc1, doc2))
print('문서 1과 문서3의 유사도 :',cos_sim(doc1, doc3))
print('문서 2와 문서3의 유사도 :',cos_sim(doc2, doc3))

문서 1과 문서2의 유사도 : 0.6666666666666667
문서 1과 문서3의 유사도 : 0.6666666666666667
문서 2와 문서3의 유사도 : 1.0000000000000002


In [28]:
# 5.02. Various Similarity Methods
"""
one-line summary : Euclidean distance is a metric that calculates the straight-line distance between two points.
Jaccard similarity is a metric that measures the ratio of the size of the intersection to the size of the union of two sets.

connection or question : Is jaccard similarity more efficient than cosine similarity?
"""

'\none-line summary : Euclidean distance is a metric that calculates the straight-line distance between two points.\nJaccard similarity is a metric that measures the ratio of the size of the intersection to the size of the union of two sets.\n\nconnection or question : Is jaccard similarity more efficient than cosine similarity?\n'

In [29]:
import numpy as np

def dist(x,y):   
    return np.sqrt(np.sum((x-y)**2))

doc1 = np.array((2,3,0,1))
doc2 = np.array((1,2,3,1))
doc3 = np.array((2,1,2,2))
docQ = np.array((1,1,0,1))

print('문서1과 문서Q의 거리 :',dist(doc1,docQ))
print('문서2과 문서Q의 거리 :',dist(doc2,docQ))
print('문서3과 문서Q의 거리 :',dist(doc3,docQ))

문서1과 문서Q의 거리 : 2.23606797749979
문서2과 문서Q의 거리 : 3.1622776601683795
문서3과 문서Q의 거리 : 2.449489742783178


In [30]:
doc1 = "apple banana everyone like likey watch card holder"
doc2 = "apple banana coupon passport love you"

# 토큰화
tokenized_doc1 = doc1.split()
tokenized_doc2 = doc2.split()

print('문서1 :',tokenized_doc1)
print('문서2 :',tokenized_doc2)

문서1 : ['apple', 'banana', 'everyone', 'like', 'likey', 'watch', 'card', 'holder']
문서2 : ['apple', 'banana', 'coupon', 'passport', 'love', 'you']


In [31]:
union = set(tokenized_doc1).union(set(tokenized_doc2))
print('문서1과 문서2의 합집합 :',union)

문서1과 문서2의 합집합 : {'likey', 'watch', 'passport', 'coupon', 'banana', 'card', 'love', 'everyone', 'apple', 'you', 'like', 'holder'}


In [32]:
intersection = set(tokenized_doc1).intersection(set(tokenized_doc2))
print('문서1과 문서2의 교집합 :',intersection)

문서1과 문서2의 교집합 : {'banana', 'apple'}


In [33]:
print('자카드 유사도 :',len(intersection)/len(union))

자카드 유사도 : 0.16666666666666666
